version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: parkease-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: parkease
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: parkease-backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/parkease
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: parkease-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: